baseURL = "https://demo.statichunt.com/geeky-hugo/"
disableLanguages = ["fr"]
disqusShortname = "themefisher-template"
googleAnalytics = ""
languageCode = "zh-tw"
languageName = "TW"
paginate = "6"
summaryLength = "20"
theme = "geeky-hugo"
title = "納舉 !  | 行為科學平台"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
