about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
address = "9567 Turner Trace Apt. BC C3G8A4"
author = "Themefisher"
categories_title = "Blog Categories"
contact_form_action = "#"
copyright = "Copyright by your company"
custom_script = ""
description = "This is meta description"
email = "info@email.com"
error_404_button = "Back To Home"
error_404_text = "404 Page Not Found!"
favicon = "images/favicon.png"
featured_post_button = "Featured"
featured_post_title = "Featured Post"
footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
image = "images/logo.png"
logo = "images/logo1.jpg"
logo_text = "Geeky"
logo_width = "150x"
mainSections = ["blog"]
mobile = "+211234565523"
navbar_fixed = false
next_button = "Next"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"
posts_title = "Featured"
previous_button = "Previous"
read_more_button = "Read more"
recent_post_button = "Recent"
recent_post_title = "Recent Post"
related_posts = "Related Posts"
search = true
showing_posts = "Showing Post From"
theme_copyright = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "關於我"
button_link = "about/"
content = "歡迎來到華文界第一個行為科學知識平台！透過這個平台，你可以掌握行為科學界最新的研究趨勢與發展，並深入瞭解行為科學的實用理論，我們期待與您共同探索行為科學的奧秘！"
enable = true
image = "/images/image3.png"
title_large = "Welcome to 納舉 **!**"
title_small = "行為科學平台"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
newsletter_button = "Sign in"
newsletter_invitation = "Join thousands of Tiny Salt subscribers and get our best recipes delivered each week!"
newsletter_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "By Singing Up, You Agree To"
newsletter_reminder_b = "Privacy Policy"
newsletter_title = "Newsletter"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
